MagicVilla_Web/Controllers/VillaController.cs
using AutoMapper;
using Azure;
using MagicVilla_VillaAPI.Models;
using MagicVilla_Web.Models.DTO;
using MagicVilla_Web.services.IServices;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Buffers.Text;
using System;
using System.Collections.Generic;
using static System.Runtime.InteropServices.JavaScript.JSType;
using System.Reflection.PortableExecutable;
using Microsoft.AspNetCore.Authorization;
using MagicVilla_Utility;

namespace MagicVilla_Web.Controllers
{
    public class VillaController : Controller
    {
        private readonly IVillaService _villaService;
        private readonly IMapper _mapper;

        public VillaController(IVillaService villaService, IMapper mapper)
        {
            _villaService = villaService;
            _mapper = mapper;
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> IndexVilla()
        {
            List<VillaDTO> list = new();

            var response = await _villaService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));

            if (response != null && response.IsSucces)
            {
                list = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(response.Result));
            }

            if (response.StatusCode == System.Net.HttpStatusCode.Unauthorized)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(list);
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> CreateVilla()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        /*
        IActionResult is an interface that allows controller actions to return various HTTP responses dynamically.
        It provides greater flexibility by enabling actions to return different HTTP status codes and response types based
        on runtime conditions.We will get the following Benefits from Using IActionResult.
        It allows actions to return different HTTP responses (e.g., Ok(), NotFound(), BadRequest())
        from a single action method dynamically based on runtime conditions.
        It allows actions to control the exact response details, such as status codes, headers, and content.
        With IActionResult as the return type, we can easily handle and return error responses like StatusCode(500).

        IActionResult is an interface in ASP.NET Core that represents the result of an action method.
        It allows you to return various types of responses, such as views, JSON, files, and more.
        The View() method is one of the ways to return a view from an action method.

        IActionResult is an interface that defines a contract for the result of an action method.
        It allows for the return of any specific result types that implement the IActionResult interface, providing maximum flexibility
        */

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> CreateVilla(VillaCreateDTO model)
        {
            if (ModelState.IsValid)
            {
                var response = await _villaService.CreateAsync<APIResponse>(model, HttpContext.Session.GetString(SD.SessionToken));

                if (response != null && response.IsSucces)
                {
                    TempData["success"] = "Villa created succesfully";

                    return RedirectToAction(nameof(IndexVilla));
                }
            }

            TempData["error"] = "Error encountered.";

            return View(model);
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateVilla(int villaId)
        {
            var response = await _villaService.GetAsync<APIResponse>(villaId, HttpContext.Session.GetString(SD.SessionToken));

            if (response != null && response.IsSucces)
            {
                VillaDTO model = JsonConvert.DeserializeObject<VillaDTO>(Convert.ToString(response.Result));

                VillaUpdateDTO villaUpdateDTO = _mapper.Map<VillaUpdateDTO>(model);

                return View(villaUpdateDTO);
            }

            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateVilla(VillaUpdateDTO model)
        {
            if (ModelState.IsValid)
            {
                var response = await _villaService.UpdateAsync<APIResponse>(model, HttpContext.Session.GetString(SD.SessionToken));

                if (response != null && response.IsSucces)
                {
                    TempData["success"] = "Villa update succesfully";
                    return RedirectToAction(nameof(IndexVilla));
                }
            }

            TempData["error"] = "Error encountered.";

            return View(model);
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteVilla(int villaId)
        {
            var response = await _villaService.GetAsync<APIResponse>(villaId, HttpContext.Session.GetString(SD.SessionToken));

            if (response != null && response.IsSucces)
            {
                VillaDTO model = JsonConvert.DeserializeObject<VillaDTO>(Convert.ToString(response.Result));

                return View(model);
            }

            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteVilla(VillaDTO model)
        {
            var response = await _villaService.DeleteAsync<APIResponse>(model.Id, HttpContext.Session.GetString(SD.SessionToken));

            if (response != null && response.IsSucces)
            {
                TempData["success"] = "Villa delete succesfully";

                return RedirectToAction(nameof(IndexVilla));
            }

            TempData["error"] = "Error encountered.";

            return View(model);
        }
    }
}

MagicVilla_Web/Controllers/VillaNumberController.cs
using AutoMapper;
using MagicVilla_Utility;
using MagicVilla_Web.Models;
using MagicVilla_Web.Models.DTO;
using MagicVilla_Web.Models.VM;
using MagicVilla_Web.services;
using MagicVilla_Web.services.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;

namespace MagicVilla_Web.Controllers
{
    public class VillaNumberController : Controller
    {
        private readonly IVillaNumberService _villaNumberService;
        private readonly IVillaService _villaService;
        private readonly IMapper _mapper;
        public VillaNumberController(IVillaNumberService villaNumberService, IMapper mapper, IVillaService villaService)
        {
            _villaNumberService = villaNumberService;
            _villaService = villaService;
            _mapper = mapper;
        }

        [Authorize(Roles = "admin")]
        [HttpGet]
        public async Task<IActionResult> IndexVillaNumber()
        {
            List<VillaNumberDTO> list = new();

            var response = await _villaNumberService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));

            if(response != null && response.IsSucces)
            {
                list = JsonConvert.DeserializeObject<List<VillaNumberDTO>>(Convert.ToString(response.Result));
            }

            return View(list);
        }

        [Authorize(Roles = "admin")]
        [HttpGet]
        public async Task<IActionResult> CreateVillaNumber()
        {
            VillaNumberCreateVM villaNumberVM = new();

            var response = await _villaService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));

            if (response != null && response.IsSucces)
            {
                villaNumberVM.VillaList = JsonConvert.DeserializeObject<List<VillaDTO>>
                    (Convert.ToString(response.Result)).Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    });
            }

            return View(villaNumberVM);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public async Task<IActionResult> CreateVillaNumber(VillaNumberCreateVM model)
        {
            if (ModelState.IsValid)
            {
                var response = await _villaNumberService.CreateAsync<APIResponse>(model.VillaNumber, HttpContext.Session.GetString(SD.SessionToken));

                if (response != null && response.IsSucces)
                {
                    return RedirectToAction(nameof(IndexVillaNumber));
                }
                else
                {
                    if (response.ErrorMessage.Count > 0)
                    {
                        ModelState.AddModelError("CustomError", response.ErrorMessage.FirstOrDefault());
                    }
                }
            }

            var res = await _villaService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));

            if (res != null && res.IsSucces)
            {
                model.VillaList = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(res.Result)).Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                });
            }

            return View(model);
        }

        [Authorize(Roles = "admin")]
        [HttpGet]
        public async Task<IActionResult> UpdateVillaNumber(int villaNo)
        {
            VillaNumberUpdateVM VillaNumberUpdateVM = new();

            var response = await _villaNumberService.GetAsync<APIResponse>(villaNo, HttpContext.Session.GetString(SD.SessionToken));

            if (response != null && response.IsSucces)
            {
                VillaNumberDTO model = JsonConvert.DeserializeObject<VillaNumberDTO>(Convert.ToString(response.Result));

                VillaNumberUpdateVM.VillaNumber = _mapper.Map<VillaNumberUpdateDTO>(model);
            }

            var responseVillaList = await _villaService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));

            if (responseVillaList != null && responseVillaList.IsSucces)
            {
                //Il metodo JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(response.Result)) deserializza la risposta
                //response.Result in una lista di oggetti di tipo VillaDTO. La funzione Convert.ToString()
                //viene utilizzata per convertire il risultato in una stringa prima della deserializzazione

                //La lista deserializzata viene trasformata in una collezione di oggetti SelectListItem.
                //Utilizzando il metodo Select(), ogni elemento della lista (i di tipo VillaDTO) viene mappato
                //a un nuovo oggetto SelectListItem

                //La proprietà Text del SelectListItem viene impostata sul valore della proprietà Name dell'oggetto VillaDTO.

                //La proprietà Value del SelectListItem viene impostata sul valore della proprietà Id dell'oggetto VillaDTO,
                //convertito in stringa con il metodo ToString().

                VillaNumberUpdateVM.VillaList = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(responseVillaList.Result)).Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                });

                return View(VillaNumberUpdateVM);
            }

            return NotFound();
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateVillaNumber(VillaNumberUpdateVM model)
        {
            if (ModelState.IsValid)
            {
                var response = await _villaNumberService.UpdateAsync<APIResponse>(model.VillaNumber, HttpContext.Session.GetString(SD.SessionToken));

                if (response != null && response.IsSucces)
                {
                    return RedirectToAction(nameof(IndexVillaNumber));
                }
                else
                {
                    if (response.ErrorMessage.Count > 0)
                    {
                        ModelState.AddModelError("ErrorMessage", response.ErrorMessage.FirstOrDefault());
                    }
                }
            }

            var errorResponse = await _villaService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));

            if (errorResponse != null && errorResponse.IsSucces)
            {
                model.VillaList = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(errorResponse.Result))
                    .Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    });
            }

            return View(model);
        }

        [Authorize(Roles = "admin")]
        [HttpGet]
        public async Task<IActionResult> DeleteVillaNumber(int villaNo)
        {
            VillaNumberDeleteVM villaNumberDeleteVM = new();

            var response = await _villaNumberService.GetAsync<APIResponse>(villaNo, HttpContext.Session.GetString(SD.SessionToken));

            if (response != null && response.IsSucces)
            {
                VillaNumberDTO model = JsonConvert.DeserializeObject<VillaNumberDTO>(Convert.ToString(response.Result));

                villaNumberDeleteVM.VillaNumber = model;
            }

            var responseVillaList = await _villaService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));

            if (responseVillaList != null && responseVillaList.IsSucces)
            {
                //Il metodo JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(response.Result)) deserializza la risposta
                //response.Result in una lista di oggetti di tipo VillaDTO. La funzione Convert.ToString()
                //viene utilizzata per convertire il risultato in una stringa prima della deserializzazione

                //La lista deserializzata viene trasformata in una collezione di oggetti SelectListItem.
                //Utilizzando il metodo Select(), ogni elemento della lista (i di tipo VillaDTO) viene mappato
                //a un nuovo oggetto SelectListItem

                //La proprietà Text del SelectListItem viene impostata sul valore della proprietà Name dell'oggetto VillaDTO.

                //La proprietà Value del SelectListItem viene impostata sul valore della proprietà Id dell'oggetto VillaDTO,
                //convertito in stringa con il metodo ToString().

                villaNumberDeleteVM.VillaList = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(responseVillaList.Result)).Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                });

                return View(villaNumberDeleteVM);
            }

            return NotFound();
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteVillaNumber(VillaNumberDeleteVM model)
        {
            var response = await _villaNumberService.DeleteAsync<APIResponse>(model.VillaNumber.VillaNo, HttpContext.Session.GetString(SD.SessionToken));

            if (response != null && response.IsSucces)
            {
                return RedirectToAction(nameof(IndexVillaNumber));
            }

            return View(model);
        }
    }
}

MagicVilla_Web/Views/VillaNumber/CreateVillaNumber.cshtml
@model MagicVilla_Web.Models.VM.VillaNumberCreateVM

<form asp-action="CreateVillaNumber">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Create Villa</h1>
        <hr />

        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <!-- VillaNo -->
            <div class="col-2">
                <label asp-for="VillaNumber.VillaNo" class="control-label pt-2" style="font-size:20px"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="VillaNumber.VillaNo" class="form-control" />
                <span asp-validation-for="VillaNumber.VillaNo" class="text-danger"></span>
            </div>

            <!-- VillaID -->
            <div class="col-2">
                <label asp-for="VillaNumber.VillaID" class="control-label pt-2" style="font-size:20px"></label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="VillaNumber.VillaID" class="form-select" asp-items="@Model.VillaList">
                    <option disabled selected>Select villa</option>
                </select>
                <span asp-validation-for="VillaNumber.VillaID" class="text-danger"></span>
            </div>

            <!-- Special details -->
            <div class="col-2">
                <label asp-for="VillaNumber.SpecialDetails" class="control-label pt-2" style="font-size:20px"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="VillaNumber.SpecialDetails" class="form-control" />
                <span asp-validation-for="VillaNumber.SpecialDetails" class="text-danger"></span>
            </div>

            <div class="col-5 offset-2">
                <a asp-action="IndexVilla" asp-controller="Villa" class="btn-primary btn form-control">Back to list</a>
            </div>

            <div class="col-5">
                <input type="submit" value="Create" class="btn btn-success form-control">
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

MagicVilla_Web/Views/VillaNumber/DeleteVillaNumber.cshtml
@model MagicVilla_Web.Models.VM.VillaNumberDeleteVM

<form asp-action="DeleteVillaNumber">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Create Villa Number</h1>
        <hr />

        <input type="hidden" asp-for="VillaNumber.VillaNo" />

        <div class="row">
            <!-- VillaNo -->
            <div class="col-2">
                <label asp-for="VillaNumber.VillaNo" class="control-label pt-2" style="font-size:20px"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="VillaNumber.VillaNo" disabled class="form-control" />
            </div>

            <!-- VillaID -->
            <div class="col-2">
                <label asp-for="VillaNumber.VillaID" class="control-label pt-2" style="font-size:20px"></label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="VillaNumber.VillaID" class="form-select" disabled asp-items="@Model.VillaList">
                    <option disabled selected>Select villa</option>
                </select>
            </div>

            <!-- Special details -->
            <div class="col-2">
                <label asp-for="VillaNumber.SpecialDetails" class="control-label pt-2" style="font-size:20px"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="VillaNumber.SpecialDetails" disabled class="form-control" />
            </div>

            <div class="col-5 offset-2">
                <a asp-action="IndexVillaNumber" asp-controller="VillaNumber" class="btn-primary btn form-control">Back to list</a>
            </div>

            <div class="col-5">
                <input type="submit" value="Delete" class="btn btn-success form-control">
            </div>
        </div>
    </div>
</form>

@section Scripts {
        <partial name="_ValidationScriptsPartial" />
}

MagicVilla_Web/Views/VillaNumber/IndexVillaNumber.cshtml
@model IEnumerable<MagicVilla_Web.Models.DTO.VillaNumberDTO>
<br />

<div class="container p-4 border">
    <div class="row pb-2">
        <div class="col">
            <h1 class="text-primary">Villa number list</h1>
        </div>
        <div class="col text-end pt-1">
            <a asp-controller="VillaNumber" asp-action="CreateVillaNumber" class="btn btn-outline-primary">Create New Villa Number</a>
        </div>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>
                    Villa Name
                </th>
                <th>
                    Villa Number
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach(var item in Model)
            {
                <tr>
                    <td>@item.Villa.Name</td>
                    <td>@item.VillaNo</td>
                    <td>
                        <a asp-controller="VillaNumber" asp-action="UpdateVillaNumber" asp-route-villaNo="@item.VillaNo" class="btn btn-success"><i class="bi bi-file-earmark-plus-fill"></i></a>
                        <a asp-controller="VillaNumber" asp-action="DeleteVillaNumber" asp-route-villaNo="@item.VillaNo" class="btn btn-danger"><i class="bi bi-trash-fill"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

MagicVilla_Web/Views/VillaNumber/UpdateVillaNumber.cshtml
@model MagicVilla_Web.Models.VM.VillaNumberUpdateVM

<form asp-action="UpdateVillaNumber">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Update Villa Number</h1>
        <hr />
        <input type="hidden" asp-for="VillaNumber.VillaNo" />
        <div class="row">
            <div asp-validation-summary="All" class="text-danger"></div>

            <!-- VillaNo -->
            <div class="col-2">
                <label asp-for="VillaNumber.VillaNo" class="control-label pt-2" style="font-size:20px"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="VillaNumber.VillaNo" disabled class="form-control" />
                <span asp-validation-for="VillaNumber.VillaNo" class="text-danger"></span>
            </div>

            <!-- VillaID -->
            <div class="col-2">
                <label asp-for="VillaNumber.VillaID" class="control-label pt-2" style="font-size:20px"></label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="VillaNumber.VillaID" class="form-select" asp-items="@Model.VillaList">
                    <option disabled selected>Select villa</option>
                </select>
                <span asp-validation-for="VillaNumber.VillaID" class="text-danger"></span>
            </div>

            <!-- Special details -->
            <div class="col-2">
                <label asp-for="VillaNumber.SpecialDetails" class="control-label pt-2" style="font-size:20px"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="VillaNumber.SpecialDetails" class="form-control" />
                <span asp-validation-for="VillaNumber.SpecialDetails" class="text-danger"></span>
            </div>

            <div class="col-5 offset-2">
                <a asp-action="IndexVillaNumber" asp-controller="VillaNumber" class="btn-primary btn form-control">Back to list</a>
            </div>

            <div class="col-5">
                <input type="submit" value="Update" class="btn btn-success form-control">
            </div>
        </div>
    </div>
</form>

@section Scripts {
        <partial name="_ValidationScriptsPartial" />
}